/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimateIcon: typeof import('./src/components/icon/AnimateIcon.vue')['default']
    BookLoading: typeof import('./src/components/icon/BookLoading.vue')['default']
    CircleLoader: typeof import('./src/components/icon/CircleLoader.vue')['default']
    ComprehensiveWord: typeof import('./src/components/words/mode/ComprehensiveWord.vue')['default']
    DictionaryBookDisplay: typeof import('./src/components/display/DictionaryBookDisplay.vue')['default']
    DictionaryDisplay: typeof import('./src/components/display/DictionaryDisplay.vue')['default']
    DictSelector: typeof import('./src/components/words/DictSelector.vue')['default']
    ExitButton: typeof import('./src/components/ExitButton.vue')['default']
    IndexCourse: typeof import('./src/components/display/IndexCourse.vue')['default']
    LeafBackground: typeof import('./src/components/display/LeafBackground.vue')['default']
    LeafButton: typeof import('./src/components/button/LeafButton.vue')['default']
    LeafCard: typeof import('./src/components/display/LeafCard.vue')['default']
    LineArrow: typeof import('./src/components/LineArrow.vue')['default']
    LineLoading: typeof import('./src/components/chore/LineLoading.vue')['default']
    Logo: typeof import('./src/components/chore/Logo.vue')['default']
    MoCodeMirror: typeof import('./src/components/editor/MoCodeMirror.vue')['default']
    MoContentRender: typeof import('./src/components/editor/MoContentRender.vue')['default']
    ModeDisplay: typeof import('./src/components/display/ModeDisplay.vue')['default']
    ModeSelector: typeof import('./src/components/words/ModeSelector.vue')['default']
    PlanSelector: typeof import('./src/components/words/PlanSelector.vue')['default']
    PlayIcon: typeof import('./src/components/icon/PlayIcon.vue')['default']
    RoundInfo: typeof import('./src/components/display/RoundInfo.vue')['default']
    RoutePage: typeof import('./src/components/page/RoutePage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/input/SearchBar.vue')['default']
    SignCalendar: typeof import('./src/components/SignCalendar.vue')['default']
    SignCalendarMonthly: typeof import('./src/components/SignCalendarMonthly.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TouchDialog: typeof import('./src/components/dialog/TouchDialog.vue')['default']
    VersionBar: typeof import('./src/components/chore/VersionBar.vue')['default']
    WithPage: typeof import('./src/components/page/WithPage.vue')['default']
    WordCard: typeof import('./src/components/WordCard.vue')['default']
    WordDetailContent: typeof import('./src/components/words/WordDetailContent.vue')['default']
    WordExamples: typeof import('./src/components/WordExamples.vue')['default']
    WordIndexBanner: typeof import('./src/components/words/WordIndexBanner.vue')['default']
    WordPlayIcon: typeof import('./src/components/icon/WordPlayIcon.vue')['default']
    WordSection: typeof import('./src/components/words/WordSection.vue')['default']
    WordSelector: typeof import('./src/components/words/WordSelector.vue')['default']
    WordSigned: typeof import('./src/components/words/page/WordSigned.vue')['default']
    WordSignInfo: typeof import('./src/components/words/WordSignInfo.vue')['default']
    WordSignInfoCard: typeof import('./src/components/words/card/WordSignInfoCard.vue')['default']
  }
}
