/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/dictionary': RouteRecordInfo<'/dictionary', '/dictionary', Record<never, never>, Record<never, never>>,
    '/editor/': RouteRecordInfo<'/editor/', '/editor', Record<never, never>, Record<never, never>>,
    '/editor/merge': RouteRecordInfo<'/editor/merge', '/editor/merge', Record<never, never>, Record<never, never>>,
    '/explore/': RouteRecordInfo<'/explore/', '/explore', Record<never, never>, Record<never, never>>,
    '/explore/comprehensive': RouteRecordInfo<'/explore/comprehensive', '/explore/comprehensive', Record<never, never>, Record<never, never>>,
    '/hi/[name]': RouteRecordInfo<'/hi/[name]', '/hi/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/old': RouteRecordInfo<'/old', '/old', Record<never, never>, Record<never, never>>,
    '/personal': RouteRecordInfo<'/personal', '/personal', Record<never, never>, Record<never, never>>,
    '/prewords': RouteRecordInfo<'/prewords', '/prewords', Record<never, never>, Record<never, never>>,
    '/words/': RouteRecordInfo<'/words/', '/words', Record<never, never>, Record<never, never>>,
    '/words/signed': RouteRecordInfo<'/words/signed', '/words/signed', Record<never, never>, Record<never, never>>,
  }
}
