export const pronounceWords = [
  { word: 'international', phonetic: '/ˌɪntəˈnæʃnəl/' },
  { word: 'organization', phonetic: '/ˌɔːɡənaɪˈzeɪʃn/' },
  { word: 'communication', phonetic: '/kəˌmjuːnɪˈkeɪʃn/' },
  { word: 'independent', phonetic: '/ˌɪndɪˈpendənt/' },
  { word: 'transportation', phonetic: '/ˌtrænspɔːˈteɪʃn/' },
  { word: 'similarity', phonetic: '/ˌsɪməˈlærəti/' },
  { word: 'unforgettable', phonetic: '/ˌʌnfəˈɡetəbl/' },
  { word: 'opportunity', phonetic: '/ˌɒpəˈtjuːnəti/' },
  { word: 'apologise', phonetic: '/əˈpɒlədʒaɪz/' },
  { word: 'preparation', phonetic: '/ˌprepəˈreɪʃn/' },
  { word: 'professional', phonetic: '/prəˈfeʃənl/' },
  { word: 'competitor', phonetic: '/kəmˈpetɪtə(r)/' },
  { word: 'disagreement', phonetic: '/ˌdɪsəˈɡriːmənt/' },
  { word: 'environmental', phonetic: '/ɪnˌvaɪrənˈmentl/' },
  { word: 'announcement', phonetic: '/əˈnaʊnsmənt/' },
  { word: 'intelligence', phonetic: '/ɪnˈtelɪdʒəns/' },
  { word: 'invitation', phonetic: '/ˌɪnvɪˈteɪʃn/' },
  { word: 'commercial', phonetic: '/kəˈmɜːʃl/' },
  { word: 'generation', phonetic: '/ˌdʒenəˈreɪʃn/' },
  { word: 'destruction', phonetic: '/dɪˈstrʌkʃn/' },
  { word: 'dormitory', phonetic: '/ˈdɔːmətri/' },
  { word: 'application', phonetic: '/ˌæplɪˈkeɪʃn/' },
  { word: 'disadvantage', phonetic: '/ˌdɪsədˈvɑːntɪdʒ/' },
  { word: 'conclusion', phonetic: '/kənˈkluːʒn/' },
  { word: 'thunderstorm', phonetic: '/ˈθʌndəstɔːm/' },
  { word: 'experiment', phonetic: '/ɪkˈsperɪmənt/' },
  { word: 'protection', phonetic: '/prəˈtekʃn/' },
  { word: 'agricultural', phonetic: '/ˌæɡrɪˈkʌltʃərəl/' },
  { word: 'conference', phonetic: '/ˈkɒnfərəns/' },
  { word: 'humourous', phonetic: '/ˈhjuːmərəs/' },
  { word: 'interpretation', phonetic: '/ɪnˌtɜːprɪˈteɪʃn/' },
  { word: 'appreciate', phonetic: '/əˈpriːʃieɪt/' },
  { word: 'attraction', phonetic: '/əˈtrækʃn/' },
  { word: 'conservation', phonetic: '/ˌkɒnsəˈveɪʃn/' },
  { word: 'imagination', phonetic: '/ɪˌmædʒɪˈneɪʃn/' },
  { word: 'helicopter', phonetic: '/ˈhelɪkɒptə(r)/' },
  { word: 'perspiration', phonetic: '/ˌpɜːspəˈreɪʃn/' },
  { word: 'radioactivity', phonetic: '/ˌreɪdiəʊækˈtɪvəti/' },
  { word: 'misunderstand', phonetic: '/ˌmɪsʌndəˈstænd/' },
  {
    word: 'observation',
    phonetic: '/ˌɒbzəˈveɪʃn/',
  },
  {
    word: 'exploration',
    phonetic: '/ˌekspləˈreɪʃn/',
  },
  {
    word: 'interviewee',
    phonetic: '/ˌɪntəvjuːˈiː/',
  },
  {
    word: 'introduction',
    phonetic: '/ˌɪntrəˈdʌkʃn/',
  },
  {
    word: 'atmosphere',
    phonetic: '/ˈætməsfɪə(r)/',
  },
  {
    word: 'extraordinary',
    phonetic: '/ɪkˈstrɔːdnri/',
  },
  {
    word: 'contemporary',
    phonetic: '/kənˈtemprəri/',
  },
  {
    word: 'contagious',
    phonetic: '/kənˈteɪdʒəs/',
  },
  {
    word: 'responsibility',
    phonetic: '/rɪˌspɒnsəˈbɪləti/',
  },
]
